version: "3.7"

volumes:
    pgadmin_data: {}
    metabase_data: {}

networks:
  reverseproxy:
    external: true
  backend: 
    driver: bridge

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8888
    ports:
      - "8888:8888"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - reverseproxy

  metabase:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      #MB_DB_DBNAME: metabase
      #MB_DB_PORT: ${METABASE_PORT}
      #MB_DB_USER: ${METABASE_USER}
      #MB_DB_PASS: ${METABASE_SECRET}
      #MB_DB_HOST: ${METABASE_HOST}
      # for ssl connection
      MB_DB_CONNECTION_URI: ${METABASE_PG_URI}
      MB_DB_FILE: "/metabase-data/metabase.db"
    networks:
      - reverseproxy
